os: osx
osx_image: xcode9.2
language: objective-c
script:
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 01_Transformations
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 02_Compute
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 03_MultiThread
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 04_ExecuteIndirect
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 05_FontRendering
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 06_BRDF
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 07_Tessellation
- xcodebuild -quiet -workspace "Examples_3/Unit_Tests/macOS Xcode/Unit_Tests.xcworkspace" -scheme 08_Procedural
